title: Fernando Borretti
description: Personal website
baseurl: ""
url: "https://borretti.me"

markdown: kramdown

kramdown:
  parse_block_html: true
  toc_levels: 1..2

highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: "article"
    values:
      layout: article
  - scope:
      path: "fiction"
    values:
      layout: fiction

permalink: /:categories/:title

# Custom variables

post_images: /assets/content/
